### ISSUE TITLE
stopped working after latest vscode-insider update

### ISSUE THREAD

**Issue by ctf0** [emeraldwalk/vscode-runonsave#29] opened 2019-07-18 11:30 UTC
Issue Type: <b>Bug</b>

now the commands always end up with `spawn C:\Windows\system32\cmd.exe ENOENT`

Extension version: 0.1.0
VS Code version: Code - Insiders 1.37.0-insider (52b6e7c4f58466e5b67348fb67d359f6bc3bb7e8, 2019-07-18T05:35:22.001Z)
OS version: Windows_NT x64 6.1.7601

**Comment by bmingles** [comment] 2019-07-19 02:26
Duplicate of #28

**Closed by bmingles** 2019-07-19 02:26 UTC
