### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by nextgenthemes** [emeraldwalk/vscode-runonsave#35] opened 2019-10-19 09:22 UTC
```
Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-16T10:47:27.951Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.3.5-1-default
```
1. Installed the extension.
2. Copied example config.
2. Enabled it via command palette.
3. Nothing is happening when I save files.

My config file: The entire `"emeraldwalk.runonsave"` section **is greyed out**. I do not know what that means.
```json
{
    "phpcbf.executablePath": "./vendor/bin/phpcbf",
    "editor.minimap.enabled": false,
    "zentabs.maximumOpenedTabs": 5,
    "workbench.activityBar.visible": true,
    "telemetry.enableCrashReporter": false,
    "workbench.enableExperiments": false,
    "workbench.settings.enableNaturalLanguageSearch": false,
    "git.enableSmartCommit": true,
    "emeraldwalk.runonsave": {
        "commands": [
            {
                "match": ".*",
                "isAsync": true,
                "cmd": "echo 'I run for all files.'"
            },
            {
                "match": "\\.txt$",
                "cmd": "echo 'I am a .txt file ${file}.'"
            },
            {
                "match": "\\.js$",
                "cmd": "echo 'I am a .js file ${file}.'"
            },
            {
                "match": ".*",
                "cmd": "echo 'I am ${env.USERNAME}.'"
            }
        ]
    }
}
```

**Comment by Dragod** [comment] 2020-01-31 13:52
`Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363`

Does not work for me either. On the vscode footer is saying "Run on Save done" but it actually did nothing.

`"todo-tree.highlights.enabled": true,
    "editor.fontSize": 13,
    "emeraldwalk.runonsave": {
        "commands": [
            {
                "match": ".*",
                "isAsync": true,
                "cmd": "echo 'I run for all files.'"
            },
            {
                "match": "\\.txt$",
                "cmd": "echo 'I am a .txt file ${file}.'"
            },
            {
                "match": "\\.js$",
                "cmd": "echo 'I am a .js file ${file}.'"
            },
            {
                "match": ".*",
                "cmd": "echo 'I am ${env.USERNAME}.'"
            }
        ]
    }`

**Comment by Joey92** [comment] 2020-02-03 12:58
> My config file: The entire "emeraldwalk.runonsave" section is greyed out. I do not know what that means.

That usually means there is no extension that reads the config. Be sure to install the correct extension from `emeraldwalk`. There are 3 on the marketplace. Happened to me too first..

**Comment by Dragod** [comment] 2020-02-03 16:29
Actually used another extension SaveAndRun and worked perfectly, if anyone still stuck here

**Comment by bmingles** [comment] 2020-02-10 14:08
Yes, I believe that greyed out means extension is either not installed or disabled. Closing since this doesn't seem to be an issue with the extension, but feel free to re-open if you find otherwise.

**Closed by bmingles** 2020-02-10 14:08 UTC

**Comment by dreamflasher** [comment] 2020-03-04 08:46
@bmingles Happened to me too, the problem is that there are 3 extensions called `Run on Save` – would be great if you'd add to the description that one needs to make sure to install the emeraldwalk one.

**Comment by donjajo** [comment] 2020-08-12 12:23
Not working for me either. Mine is not greyed out

```
Electron v9.1.2
Chromium v83.0.4103.122
Node v12.14.1v8 v8.3.110.13-electron.0
OS: Linux 5.7.12-arch1-1
```
